### ISSUE TITLE
Infinity Free 如何安装 Typecho 呢？ 

### ISSUE THREAD

**Issue by Borber** [arleycn/arleycn#1]
从 https://arley.fun/05.html 这里找来的， 但是不知道怎么设置安装时的database， 会显示连接不上

**Comment by arleycn** [comment]
抱歉这么晚才看到，明天回复你，把你问题具体发过来



 发自我的企业微信     
 
 &nbsp;


 ----------回复的邮件信息----------
 ***@***.***&gt; 于2022年2月3日(周四) 晚上7:47写道:

  

 
从 https://arley.fun/05.html 这里找来的， 但是不知道怎么设置安装时的database， 会显示连接不上
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by arleycn** [comment]
infinity后台应用商店里面有typecho，直接安装就好了，后面就跟在服务器安装是一样的了，数据库啥的好像要提前创建好，也是在后台应用里面

**Comment by Borber** [comment]
> infinity后台应用商店里面有typecho，直接安装就好了，后面就跟在服务器安装是一样的了，数据库啥的好像要提前创建好，也是在后台应用里面

 嗯嗯 我装好了, 就是它好像配置不够装上主题之后崩了

**Comment by arleycn** [comment]
当时我用的viid主题，没啥问题，自从infinity他们家的免费IP出问题后就没在用了



 发自我的企业微信     
 
 &nbsp;


 ----------回复的邮件信息----------
 ***@***.***&gt; 于2022年2月11日(周五) 下午3:59写道:

  

  
infinity后台应用商店里面有typecho，直接安装就好了，后面就跟在服务器安装是一样的了，数据库啥的好像要提前创建好，也是在后台应用里面
  
嗯嗯 我装好了, 就是它好像配置不够装上主题之后崩了
